### ISSUE TITLE
Iris incompatibility

### ISSUE THREAD

**Issue by BartzV** [ckosmic/minecraft-psx#3]
The shaders has not compatibility with Iris, the shader support for Sodium (Fabric)
The shader itself acts like default shader when loaded.

**Comment by akemin-dayo** [comment]
I've added Iris compatibility in my fork: https://github.com/akemin-dayo/minecraft-ps1-shaders

I've also submitted PR #4, so perhaps my changes will be merged upstream here too.

**Comment by ckosmic** [comment]
Added in https://github.com/ckosmic/minecraft-psx/pull/4
